spring:
  redis:
    host: 192.168.30.101
    port: 6379
    database: 0
#    password: ******
    jedis:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 6
        max-wait: -1

